-- =============================================
-- Author:		  Edwin Calderón
-- Create date:   18/09/2023
-- Description:	Actualiza Información de Activos Inmobiliarios
--				
-- =============================================
CREATE PROCEDURE BVQ_BACKOFFICE.ActualizarActivosInmobiliariosISSPOL
	@IMB_ID				  INT,
	@POR_CODIGO			  VARCHAR(50),
	@IMB_TIPO			  VARCHAR(1500),
	@IMB_PROVINCIA		  VARCHAR(300),
	@IMB_UBICACION		  VARCHAR(300),
	@IMB_VALOR_LIBROS	  FLOAT = NULL	,
	@IMB_VALOR_AVALUO	  FLOAT = NULL,
	@IMB_FECHA_ULT_AVALUO DATETIME = NULL,
	@IMB_FECHA_ESCRITURA  DATETIME = NULL,
	@IMB_CUENTA_CONTABLE   VARCHAR(100),
	@IMB_FORMA_ADQUISICION VARCHAR(1500),
	@i_lga_id			  INT
AS
BEGIN
	UPDATE [BVQ_BACKOFFICE].[ACTIVOS_INMOBILIARIOS]
	SET [POR_CODIGO] = @POR_CODIGO
	   ,[IMB_TIPO] = @IMB_TIPO
	   ,[IMB_PROVINCIA] = @IMB_PROVINCIA
	   ,[IMB_UBICACION] = @IMB_UBICACION
	   ,[IMB_VALOR_LIBROS] = @IMB_VALOR_LIBROS
	   ,[IMB_VALOR_AVALUO] = @IMB_VALOR_AVALUO
	   ,[IMB_FECHA_ULT_AVALUO] = @IMB_FECHA_ULT_AVALUO
	   ,[IMB_FECHA_ESCRITURA] = @IMB_FECHA_ESCRITURA
	   ,[IMB_CUENTA_CONTABLE] = @IMB_CUENTA_CONTABLE
	   ,[IMB_FORMA_ADQUISICION] = @IMB_FORMA_ADQUISICION
	WHERE IMB_ID = @IMB_ID
END