create procedure bvq_backoffice.GenerarComprobanteIsspol as
begin
	truncate table bvq_backoffice.comprobante_isspol
	insert into bvq_backoffice.comprobante_isspol
	(tpo_numeracion
	,tiv_id
	,oper
	,fecha
	,tipPap
	,cuenta
	,nombre
	,debe
	,haber
	,saldo
	,htp_compra
	,ems_nombre
	,tvl_nombre
	,fecha_compra
	,tiv_fecha_vencimiento
	,tasa_cupon
	,tiv_fecha_emision
	,rubro
	,monto
	,rubroOrd
	,valefeoper
	,hist_precio_compra
	,hist_fecha_compra
	,por_ord
	,tipo
	,aux
	,tfl_fecha_inicio_orig
	,comisiones
	,precio_efectivo
	,ICR_CODIGO
	,htp_tpo_id
	,tvl_codigo
	,ri
	,plazo
	,tfl_periodo
	,htp_fecha_operacion
	,deterioro
	,forced_por_id
	,FON_ID
	,EVP_COSTAS_JUDICIALES_REFERENCIA
	,EVP_COBRADO
	)
	select
	tpo_numeracion
	,tiv_id
	,oper
	,fecha
	,tipPap
	,cuenta
	,nombre
	,debe
	,haber
	,saldo
	,htp_compra
	,ems_nombre
	,tvl_nombre
	,fecha_compra
	,tiv_fecha_vencimiento
	,tasa_cupon
	,tiv_fecha_emision
	,rubro
	,monto
	,rubroOrd
	,valefeoper
	,hist_precio_compra
	,hist_fecha_compra
	,por_ord
	,tipo
	,aux
	,tfl_fecha_inicio_orig
	,comisiones
	,precio_efectivo
	,ICR_CODIGO
	,htp_tpo_id
	,tvl_codigo
	,ri
	,plazo
	,tfl_periodo
	,htp_fecha_operacion
	,deterioro
	,forced_por_id
	,FON_ID
	,EVP_COSTAS_JUDICIALES_REFERENCIA
	,EVP_COBRADO
	from bvq_backoffice.comprobanteisspol where fecha>='20230101'
end
