CREATE PROCEDURE [BVQ_BACKOFFICE].[GuardarPAIMonto]
    @i_periodo       VARCHAR(100),
    @i_tabla_nombre  VARCHAR(500),
    @i_tabla_orden   INT,
    @i_tipo_nombre   VARCHAR(200),
    @i_tipo_orden    INT,
    @i_fondo_nombre  VARCHAR(200),
    @i_fondo_orden   INT,
    @i_monto         FLOAT,
    @i_lga_id        INT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @PAI_ID INT, @TAB_ID INT, @TIP_ID INT, @FOP_ID INT;
    DECLARE @TIP_CODIGO_RESUELTO VARCHAR(50), @FOP_CODIGO_RESUELTO VARCHAR(50);

    SELECT @TIP_CODIGO_RESUELTO = PCP_CODIGO FROM BVQ_BACKOFFICE.PAI_CODIGO_PRESTABLECIDO
    WHERE PCP_TIPO = 'TIPO_INVERSION' AND LTRIM(RTRIM(PCP_NOMBRE)) = LTRIM(RTRIM(@i_tipo_nombre));

    SELECT @FOP_CODIGO_RESUELTO = PCP_CODIGO FROM BVQ_BACKOFFICE.PAI_CODIGO_PRESTABLECIDO
    WHERE PCP_TIPO = 'FONDO' AND LTRIM(RTRIM(PCP_NOMBRE)) = LTRIM(RTRIM(@i_fondo_nombre));

    SELECT @PAI_ID = PAI_ID FROM BVQ_BACKOFFICE.PAI_GENERAL WHERE PAI_PERIODO = @i_periodo;
    IF @PAI_ID IS NULL
    BEGIN
        INSERT INTO BVQ_BACKOFFICE.PAI_GENERAL (PAI_PERIODO) VALUES (@i_periodo);
        SET @PAI_ID = SCOPE_IDENTITY();
    END

    SELECT @TAB_ID = TAB_ID FROM BVQ_BACKOFFICE.PAI_TABLA WHERE PAI_ID = @PAI_ID AND TAB_NOMBRE = @i_tabla_nombre;
    IF @TAB_ID IS NULL
    BEGIN
        INSERT INTO BVQ_BACKOFFICE.PAI_TABLA (PAI_ID, TAB_NOMBRE, TAB_ORDEN) VALUES (@PAI_ID, @i_tabla_nombre, @i_tabla_orden);
        SET @TAB_ID = SCOPE_IDENTITY();
    END
    ELSE
        UPDATE BVQ_BACKOFFICE.PAI_TABLA SET TAB_ORDEN = @i_tabla_orden WHERE TAB_ID = @TAB_ID;

    SELECT @TIP_ID = TIP_ID FROM BVQ_BACKOFFICE.PAI_TIPO_INVERSION WHERE TAB_ID = @TAB_ID AND TIP_NOMBRE = @i_tipo_nombre;
    IF @TIP_ID IS NULL
    BEGIN
        INSERT INTO BVQ_BACKOFFICE.PAI_TIPO_INVERSION (TAB_ID, TIP_NOMBRE, TIP_CODIGO, TIP_ORDEN) VALUES (@TAB_ID, @i_tipo_nombre, @TIP_CODIGO_RESUELTO, @i_tipo_orden);
        SET @TIP_ID = SCOPE_IDENTITY();
    END
    ELSE
        UPDATE BVQ_BACKOFFICE.PAI_TIPO_INVERSION SET TIP_CODIGO = @TIP_CODIGO_RESUELTO, TIP_ORDEN = @i_tipo_orden WHERE TIP_ID = @TIP_ID;

    SELECT @FOP_ID = FOP_ID FROM BVQ_BACKOFFICE.PAI_FONDO WHERE TAB_ID = @TAB_ID AND FOP_NOMBRE = @i_fondo_nombre;
    IF @FOP_ID IS NULL
    BEGIN
        INSERT INTO BVQ_BACKOFFICE.PAI_FONDO (TAB_ID, FOP_NOMBRE, FOP_CODIGO, FOP_ORDEN) VALUES (@TAB_ID, @i_fondo_nombre, @FOP_CODIGO_RESUELTO, @i_fondo_orden);
        SET @FOP_ID = SCOPE_IDENTITY();
    END
    ELSE
        UPDATE BVQ_BACKOFFICE.PAI_FONDO SET FOP_CODIGO = @FOP_CODIGO_RESUELTO, FOP_ORDEN = @i_fondo_orden WHERE FOP_ID = @FOP_ID;

    IF EXISTS (SELECT 1 FROM BVQ_BACKOFFICE.PAI_MONTO WHERE TAB_ID = @TAB_ID AND TIP_ID = @TIP_ID AND FOP_ID = @FOP_ID)
        UPDATE BVQ_BACKOFFICE.PAI_MONTO SET PAIM_MONTO = @i_monto WHERE TAB_ID = @TAB_ID AND TIP_ID = @TIP_ID AND FOP_ID = @FOP_ID;
    ELSE
        INSERT INTO BVQ_BACKOFFICE.PAI_MONTO (TAB_ID, TIP_ID, FOP_ID, PAIM_MONTO) VALUES (@TAB_ID, @TIP_ID, @FOP_ID, @i_monto);

    EXEC [BVQ_SEGURIDAD].[RegistrarAuditoria]
        @i_lga_id = @i_lga_id,
        @i_tabla = 'PAI_MONTO',
        @i_esquema = N'BVQ_BACKOFFICE',
        @i_operacion = N'I',
        @i_subTipo = N'N',
        @i_columIdName = 'PAIM_ID',
        @i_idAfectado = @@IDENTITY
END
