-- =============================================
-- Author:		  Edwin Calderón
-- Create date:   18/09/2023
-- Description:	Inserta Información de Activos Inmobiliarios
--				
-- =============================================
CREATE PROCEDURE BVQ_BACKOFFICE.InsertarActivosInmobiliariosISSPOL
	@POR_CODIGO			   VARCHAR(50),
	@IMB_TIPO			   VARCHAR(1500),
	@IMB_PROVINCIA		   VARCHAR(300),
	@IMB_UBICACION		   VARCHAR(300),
	@IMB_VALOR_LIBROS	   FLOAT = NULL	,
	@IMB_VALOR_AVALUO	   FLOAT = NULL,
	@IMB_FECHA_ULT_AVALUO  DATETIME = NULL,
	@IMB_FECHA_ESCRITURA   DATETIME = NULL,
	@IMB_CUENTA_CONTABLE   VARCHAR(100),
	@IMB_FORMA_ADQUISICION VARCHAR(1500),
	@i_lga_id			  INT
AS
BEGIN
	INSERT INTO [BVQ_BACKOFFICE].[ACTIVOS_INMOBILIARIOS] ([POR_CODIGO],
	[IMB_TIPO],
	[IMB_PROVINCIA],
	[IMB_UBICACION],
	[IMB_VALOR_LIBROS],
	[IMB_VALOR_AVALUO],
	[IMB_FECHA_ULT_AVALUO],
	[IMB_FECHA_ESCRITURA],
	[IMB_CUENTA_CONTABLE],
	[IMB_FORMA_ADQUISICION])
	VALUES (@POR_CODIGO, @IMB_TIPO, @IMB_PROVINCIA, @IMB_UBICACION, @IMB_VALOR_LIBROS, @IMB_VALOR_AVALUO, @IMB_FECHA_ULT_AVALUO, @IMB_FECHA_ESCRITURA, @IMB_CUENTA_CONTABLE, @IMB_FORMA_ADQUISICION)
END