CREATE PROCEDURE [BVQ_BACKOFFICE].[ObtenerSubtiposProyeccionDispISSPOL]
	@i_lga_id INT = NULL
AS
BEGIN
	SET NOCOUNT ON

	SELECT DISTINCT
		UPPER(ITC_VALOR) AS valor
	FROM [BVQ_ADMINISTRACION].[ITEM_CATALOGO]
	WHERE CAT_ID = 328
		AND ITC_ESTADO = 21
		AND ITC_VALOR <> '0 Saldo Inicial'
	ORDER BY valor
END