CREATE PROCEDURE [BVQ_BACKOFFICE].[ObtenerProyeccionDispDetISSPOL]
	@i_pdc_id INT,
	@i_lga_id INT = NULL
AS
BEGIN
	SET NOCOUNT ON

	SELECT
		PDD_FECHA_VENCIMIENTO AS fecha_vencimiento,
		PDD_PORTAFOLIO AS portafolio,
		PDD_SUBTIPO AS itc_valor,
		PDD_TIPO_PAPEL AS tipo_papel,
		PDD_IE AS [I/E],
		PDD_MONTO AS cupon
	FROM [BVQ_BACKOFFICE].[ISSPOL_PROYECCION_DISP_DET]
	WHERE PDD_PDC_ID = @i_pdc_id
	ORDER BY PDD_FECHA_VENCIMIENTO
END
