CREATE PROCEDURE [BVQ_BACKOFFICE].[ObtenerProyeccionDispCabISSPOL]
    @i_lga_id INT
AS
BEGIN
    SELECT
        PDC_ID, PDC_NOMBRE, PDC_FECHA_CORTE, PDC_FECHA_INICIO, PDC_FECHA_FIN
    FROM BVQ_BACKOFFICE.ISSPOL_PROYECCION_DISP_CAB
END
