CREATE PROCEDURE [BVQ_BACKOFFICE].[ObtenerFondosProyeccionDispISSPOL]
	@i_lga_id INT = NULL
AS
BEGIN
	SET NOCOUNT ON

	SELECT DISTINCT
		ICB_DESCRIPCION AS valor
	FROM [BVQ_BACKOFFICE].[ISSPOL_CUENTAS_CONTABLES_DE_BANCOS]
	WHERE ICB_DESCRIPCION IS NOT NULL
	ORDER BY valor
END