CREATE PROCEDURE [BVQ_BACKOFFICE].[ObtenerCodigosPrestablecidosPAI]
    @i_lga_id INT
AS
BEGIN
    SET NOCOUNT ON;

    SELECT PCP_TIPO, PCP_NOMBRE, PCP_CODIGO
    FROM BVQ_BACKOFFICE.PAI_CODIGO_PRESTABLECIDO
    ORDER BY PCP_TIPO, PCP_NOMBRE;
END
