CREATE PROCEDURE [BVQ_BACKOFFICE].[ObtenerTiposPapelProyeccionDispISSPOL]
	@i_lga_id INT = NULL
AS
BEGIN
	SET NOCOUNT ON

	SELECT DISTINCT
		TVL_NOMBRE AS valor
	FROM [BVQ_ADMINISTRACION].[TIPO_VALOR]
	WHERE TVL_ESTADO = 21
	ORDER BY valor
END