CREATE PROCEDURE BVQ_BACKOFFICE.spIsspolRentaVariable @i_fechaCorte datetime=null, @i_lga_id int=null as
 begin  
  delete from corteslist  
  insert into corteslist(c,cortenum)  
  select @i_fechaCorte,1  
  exec bvq_backoffice.GenerarCompraVentaFlujo  
  exec bvq_administracion.GenerarVectores  
  exec bvq_administracion.PrepararValoracionLinealCache  
  
    
  if 0=1   
   select   
   FECHA_EVALUACION=@i_fechaCorte  
  
  select   
 TVL_NOMBRE=TVL_NOMBRE,  
 CUENTA_CONTABLE=CUENTA_CONTABLE,  
 VECTOR_PRECIO=VECTOR_PRECIO,  
 TIPO=TIPO,  
 CUPON=CUPON,  
 PLAZO_PACTADO=PLAZO_PACTADO,  
 FECHA_VENCIMIENTO_CONVENIO_PAGO=FECHA_VENCIMIENTO_CONVENIO_PAGO,  
 FECHA_SUSCRIPCION_CONVENIO_PAGO=FECHA_SUSCRIPCION_CONVENIO_PAGO,  
 FECHA_VENCIMIENTO_ORIGINAL=FECHA_VENCIMIENTO_ORIGINAL,  
 EMISOR=EMISOR,  
 INTERVINIENTES=INTERVINIENTES,  
 NO_ACCIONES=sum(NO_ACCIONES),  
 VALOR_EFECTIVO=sum(VALOR_EFECTIVO),  
 INTERES_TRANSCURRIDO=sum(INTERES_TRANSCURRIDO),  
 PRECIO_DE_HOY=PRECIO_DE_HOY,  
 INTERES_ACUMULADO=sum(INTERES_ACUMULADO),  
 VALOR_DE_MERCADO=sum(NO_ACCIONES) * PRECIO_DE_HOY * 100, -- VALOR_DE_MERCADO=sum(VALOR_DE_MERCADO),   
 PCT_DEL_VALOR_DE_MERCADO=sum(PCT_DEL_VALOR_DE_MERCADO),  
 VENCER=VENCER,  
 FECHA_VALOR_DE_COMPRA=FECHA_VALOR_DE_COMPRA,  
 VALOR_EFECTIVO_HISTORICO=sum(VALOR_EFECTIVO_HISTORICO),  
 YIELD=YIELD,  
 PRECIO=PRECIO,  
 SECTOR=SECTOR,  
 MONTO_EMITIDO=MONTO_EMITIDO,  
 PATRIMONIO=PATRIMONIO,  
 CALIFICADORA_DE_RIESGO=CALIFICADORA_DE_RIESGO,  
 CALIFICACION_DE_RIESGO=CALIFICACION_DE_RIESGO,  
 VALOR_PROVISIONADO=sum(VALOR_PROVISIONADO),  
 FECHA_DE_PAGO_ULTIMO_CUPON=FECHA_DE_PAGO_ULTIMO_CUPON,  
 DIAS_DE_INTERES_GANADO=DIAS_DE_INTERES_GANADO,  
 INTERES_GANADO=sum(INTERES_GANADO),  
 INTERES_AL_VENCIMIENTO_ORIGINAL_=sum(INTERES_AL_VENCIMIENTO_ORIGINAL_),  
 INTERES_POR_DIAS_DE_RETRASO=sum(INTERES_POR_DIAS_DE_RETRASO),  
 PCT_A_AJUSTAR=PCT_A_AJUSTAR,  
 DIAS_POR_VENCER_A_LA_COMPRA=DIAS_POR_VENCER_A_LA_COMPRA,  
 PCT_AJUSTE_DIARIO=PCT_AJUSTE_DIARIO,  
 FACTOR_DE_AJUSTE=FACTOR_DE_AJUSTE,  
 CONTROLADOR_SECTOR=CONTROLADOR_SECTOR,  
 CONTROLADOR_POSICION=CONTROLADOR_POSICION,  
 PRECIO_ULTIMA_COMPRA=PRECIO_ULTIMA_COMPRA,  
 FECHA_ULTIMA_COMPRA=FECHA_ULTIMA_COMPRA,  
 BASE_PARA_DIAS_INTERES=BASE_PARA_DIAS_INTERES,  
 BASE_PARA_TASA_INTERES=BASE_PARA_TASA_INTERES,  
 VECTOR_PRECIO2=VECTOR_PRECIO2,  
 CUPON_VECTOR=CUPON_VECTOR,  
 CODIGO_TITULO=CODIGO_TITULO,  
 TIPO_VECTOR=TIPO_VECTOR,  
 VALORES_RECUPERADOS=sum(VALORES_RECUPERADOS),  
 ACCIONES_REALIZADAS=ACCIONES_REALIZADAS,  
 MANTIENE_VECTOR_PRECIO=MANTIENE_VECTOR_PRECIO,  
 ACP_ID=ACP_ID,  
 PROG=PROG,  
 FKOP=sum(FKOP),  
 ACTA=ACTA,  
 GCXC_NOMBRE=GCXC_NOMBRE,  
 TVL_CODIGO=TVL_CODIGO,  
 EMS_NOMBRE=EMS_NOMBRE,  
 TPO_F1=TPO_F1,  
 OTROS_COSTOS=OTROS_COSTOS,  
 COMISIONES=sum(COMISIONES),  
 TPO_PROG=TPO_PROG,  
 RECURSOS=RECURSOS,  
 TIV_VALOR_NOMINAL=TIV_VALOR_NOMINAL,  
 HTP_COMPRA=sum(HTP_COMPRA),  
 ABONO_INTERES=ABONO_INTERES,  
 VALNOM_ANTERIOR=VALNOM_ANTERIOR,  
 FECHA_ENCARGO=FECHA_ENCARGO,  
 DIVIDENDOS_EN_ACCIONES=DIVIDENDOS_EN_ACCIONES,  
 ORD,  
 --POR_SIGLAS = dbo.StringAGG(por_siglas, '-')  
 POR_SIGLAS = (
 SELECT STUFF((SELECT '-' + por.por_siglas
              FROM bvq_backoffice.titulos_portafolio p2
                   JOIN bvq_backoffice.portafolio por ON por.por_id = p2.por_id
              WHERE p2.tpo_numeracion = s.htp_numeracion
                    AND tpo_estado = 352
              ORDER BY por.por_ord
              FOR XML PATH('')), 1, 1, '')
 ),
 PRECIO_INFO_BASICA=MAX(PRECIO_INFO_BASICA)
  from(  
   select   
 TVL_NOMBRE=COALESCE(TVLH_TIPOSC, TVL_CODIGO ),  
 CUENTA_CONTABLE='7.1.5.90.90',  
 VECTOR_PRECIO=case when [TPO_MANTIENE_VECTOR_PRECIO]=1 or [IPR_ES_CXC]=0 then [TIV_CODIGO_VECTOR] end,  
 TIPO=TVL_DESCRIPCION,  
 CUPON=[TIV_TASA_INTERES]/100.0,  
 PLAZO_PACTADO=dbo.fnDias([FECHA_COMPRA],[TIV_FECHA_VENCIMIENTO],TIV_TIPO_BASE),  
 FECHA_VENCIMIENTO_CONVENIO_PAGO=TPO_FECHA_VEN_CONVENIO,  
 FECHA_SUSCRIPCION_CONVENIO_PAGO=TPO_FECHA_SUSC_CONVENIO,  
 FECHA_VENCIMIENTO_ORIGINAL=tiv_fecha_vencimiento,  
 EMISOR=[EMS_NOMBRE] + isnull('/' + [ACP_NOMBRE],''),  
 INTERVINIENTES=TPO_INTERVINIENTES,  
 NO_ACCIONES=sal,  
 VALOR_EFECTIVO=case when [TPO_F1]=(select top 1 kf1 from keyf1 where natkey like 'MINISTERIO DE FINANZAS|20240620|20160108|%' and kf1=339) then  
                 377916.44/873855.24*sal  
 when[TVL_CODIGO] in ('PCO') then sal*[htp_precio_compra]/100.0 else sal*[TIV_PRECIO]/100.0 end,  
 INTERES_TRANSCURRIDO=[TPO_INTERES_TRANSCURRIDO],  
 PRECIO_DE_HOY=case when tvl_codigo not in ('DER','OBL','PAG') then [TIV_PRECIO]/100.0 else null end,  
 INTERES_ACUMULADO=[dias_al_corte] * case when [TVL_CODIGO] in ('FAC','PCO') then [HTP_RENDIMIENTO] else [TIV_TASA_INTERES] end,  
 VALOR_DE_MERCADO=case when tvl_codigo='ENC' then sal else htp_compra end*htp_precio_compra,--valefe,  
 PCT_DEL_VALOR_DE_MERCADO=[valefe],  
 VENCER=datediff(d,[tfcorte],[tiv_fecha_vencimiento]),  
 FECHA_VALOR_DE_COMPRA=fecha_compra,  
 VALOR_EFECTIVO_HISTORICO=isnull([TPO_INTERES_TRANSCURRIDO],0) + isnull([TPO_COMISION_BOLSA],0) + [htp_compra]*[htp_precio_compra]/case when [tiv_tipo_renta]=153 then 100e else 1e end,  
 YIELD=CASE WHEN [TVL_CODIGO] in ('FAC','PCO') THEN [HTP_RENDIMIENTO] ELSE [TIV_TASA_INTERES] END/100.0,  
 PRECIO=htp_precio_compra,  
 SECTOR=CASE [sector_general] WHEN 'SEC_PRI_FIN' then 'PRIVADO FINANCIERO' WHEN 'SEC_PRI_NFIN' THEN 'PRIVADO NO FINANCIERO' WHEN 'SEC_PUB_FIN' THEN 'PUBLICO' WHEN 'SEC_PUB_NFIN' THEN 'PUBLICO' END,  
 MONTO_EMITIDO=[TIV_MONTO_EMISION],  
 PATRIMONIO=[VBA_PATRIMONIO_TECNICO],  
 CALIFICADORA_DE_RIESGO=coalesce(rtrim(eca_nombre)+' - '+convert(varchar,eca_fecha_resolucion,103),[CAL_NOMBRE],'NO DISPONIBLE'),  
 CALIFICACION_DE_RIESGO=coalesce(eca_valor,[ENC_VALOR],[TCA_VALOR],'NO DISPONIBLE'),  
 VALOR_PROVISIONADO=sal*[TIV_PRECIO]/100.0,  
 FECHA_DE_PAGO_ULTIMO_CUPON=latest_inicio,  
 DIAS_DE_INTERES_GANADO=case when tvl_codigo in ('FAC','PCO') and pc.tiv_tipo_base=355 and latest_inicio=fecha_compra then datediff(d,tiv_fecha_vencimiento,tfcorte) else pc.dias_al_corte end,  
 INTERES_GANADO=  
  case when tvl_codigo in ('FAC','PCO') and pc.tiv_tipo_base=355 and latest_inicio=fecha_compra then  
   datediff(d,tiv_fecha_vencimiento,tfcorte)  
  else pc.dias_al_corte end  
  *  
  CASE WHEN [TVL_CODIGO] in ('FAC','PCO','PACTO') THEN  
   (case when [TVL_CODIGO] in ('PCO') then sal*[htp_precio_compra]/100.0 else pc.valefe end + CASE WHEN TPO_INTERVINIENTES LIKE 'Capital Ventura%' THEN TPO_INTERES_TRANSCURRIDO ELSE 0 END)  
   *[HTP_RENDIMIENTO]/100.0/360.0  
  ELSE  
   (sal-isnull(TPO_VALNOM_ANTERIOR,0))  
   * [TIV_TASA_INTERES]  
   /100.0/360.0  
  END  
  - isnull(TPO_ABONO_INTERES,0)  
 ,  
 INTERES_AL_VENCIMIENTO_ORIGINAL_=CASE WHEN [TPO_FECHA_SUSC_CONVENIO] is not null THEN [sal]*datediff(d,[FECHA_COMPRA],[TIV_FECHA_VENCIMIENTO])/360.0*CASE WHEN [TVL_CODIGO] in ('FAC','PCO') THEN 0/*[HTP_RENDIMIENTO]*/ ELSE [TIV_TASA_INTERES] END/100.0 END



  
  
  
  
,  
 INTERES_POR_DIAS_DE_RETRASO=CASE WHEN [TPO_FECHA_SUSC_CONVENIO] is not null THEN sal*[TIV_PRECIO]/100.0*datediff(d,[TIV_FECHA_VENCIMIENTO],[LATEST_INICIO])/360.0*CASE WHEN [TVL_CODIGO] in ('FAC','PCO') THEN [HTP_RENDIMIENTO] ELSE [TIV_TASA_INTERES] END/100.0 END,  
 PCT_A_AJUSTAR=case when tvl_codigo not in ('DER','OBL','PAG') then 1-[TPO_PRECIO_ULTIMA_COMPRA] else null end,  
 DIAS_POR_VENCER_A_LA_COMPRA=case when tvl_codigo not in ('DER','OBL','PAG') then datediff(d,[FECHA_COMPRA],[tiv_fecha_vencimiento]) else null end,  
 PCT_AJUSTE_DIARIO=case when tvl_codigo not in ('DER','OBL','PAG') then (1-[TPO_PRECIO_ULTIMA_COMPRA])/datediff(d,[FECHA_COMPRA],[tiv_fecha_vencimiento]) else null end,  
 FACTOR_DE_AJUSTE=case when tvl_codigo not in ('DER','OBL','PAG') then (1-[TPO_PRECIO_ULTIMA_COMPRA])/datediff(d,[FECHA_COMPRA],[tiv_fecha_vencimiento])*datediff(d,[FECHA_COMPRA],[TFCORTE]) else null end,  
 CONTROLADOR_SECTOR=CASE WHEN [SECTOR_GENERAL]='SEC_PRI_FIN' THEN 1 WHEN [SECTOR_GENERAL]='SEC_PRI_NFIN' THEN 2 WHEN [SECTOR_GENERAL] IN ('SEC_PUB_FIN','SEC_PUB_NFIN') THEN 3 ELSE 0 END,  
 CONTROLADOR_POSICION=CASE  
   WHEN datediff(d,[TFCORTE],[TIV_FECHA_VENCIMIENTO]) IS NULL THEN 0  
   WHEN datediff(d,[TFCORTE],[TIV_FECHA_VENCIMIENTO])<366 THEN 1  
   WHEN datediff(d,[TFCORTE],[TIV_FECHA_VENCIMIENTO])<1096 THEN 2  
   WHEN datediff(d,[TFCORTE],[TIV_FECHA_VENCIMIENTO])<1826 THEN 3  
   WHEN datediff(d,[TFCORTE],[TIV_FECHA_VENCIMIENTO])<3651 THEN 4  
   ELSE 5 END,  
 PRECIO_ULTIMA_COMPRA=TPO_PRECIO_ULTIMA_COMPRA,  
 FECHA_ULTIMA_COMPRA=case when ipr_es_cxc=0 then tfcorte when tvl_codigo not in ('DER','OBL','PAG') then [fecha_compra] end,  
 BASE_PARA_DIAS_INTERES=CASE WHEN  
    [TIV_TIPO_BASE]=354  
    OR  
    [IPR_ES_CXC]=0 AND [TVL_CODIGO] NOT IN ('PCO')  
   THEN '360' WHEN [tiv_tipo_base]=355 THEN'REAL' ELSE '' END,  
 BASE_PARA_TASA_INTERES=360,  
 VECTOR_PRECIO2=case when TPO_MANTIENE_VECTOR_PRECIO=1 OR tiv_codigo_vector<>'' then [tiv_precio]/100.0 end,  
 CUPON_VECTOR=TPO_CUPON_VECTOR,  
 CODIGO_TITULO=[TPO_CODIGO_VECTOR],  
 TIPO_VECTOR=case when TPO_MANTIENE_VECTOR_PRECIO=1 OR tiv_codigo_vector<>'' then [TVL_CODIGO] + ' ' + CASE WHEN [tvl_codigo]='swap' THEN [TPO_ACTA] else [TIV_CLASE] END end,  
 VALORES_RECUPERADOS=[htp_compra]-[sal],  
 ACCIONES_REALIZADAS=[TPO_OBJETO],  
 MANTIENE_VECTOR_PRECIO=TPO_MANTIENE_VECTOR_PRECIO,  
 ACP_ID=ACP_ID,  
 PROG=TPO_PROG,  
 FKOP=TPO_FKOP,  
 ACTA=TPO_ACTA,  
 GCXC_NOMBRE=[GCXC_NOMBRE],  
 TVL_CODIGO=[TVL_CODIGO],  
 EMS_NOMBRE=[EMS_NOMBRE],  
 TPO_F1=case when tvl_codigo='ENC' then 1 else 0 end *100000000 + datediff(d,'20120101',fecha_compra)*1000+isnull(tpo_f1,0), --','+format(fecha_compra,'yyyyMMdd')+','+rtrim(TPO_F1),--[TPO_F1],  
 OTROS_COSTOS=TPO_OTROS_COSTOS,  
 COMISIONES=TPO_COMISION_BOLSA,  
 TPO_PROG=[TPO_PROG],  
 RECURSOS=[TPO_RECURSOS],  
 TIV_VALOR_NOMINAL=coalesce(VNU_VALOR,[TIV_VALOR_NOMINAL]),  
 HTP_COMPRA=[htp_compra],  
 ABONO_INTERES=TPO_ABONO_INTERES,  
 VALNOM_ANTERIOR=TPO_VALNOM_ANTERIOR,  
 FECHA_ENCARGO=TPO_FECHA_ENCARGO,  
 DIVIDENDOS_EN_ACCIONES=pc.TPO_DIVIDENDOS_EN_ACCIONES,--  
 ORD=case when tvl_codigo='FI' then 1 else 0 end ,
 --por_siglas = por_siglas  
 port.por_ord as orden,
pc.htp_numeracion,
PRECIO_INFO_BASICA=1.0
  --select * from rvout where cname like '%calif%'  
   from bvq_backoffice.portafoliocorte pc  
   join BVQ_BACKOFFICE.PORTAFOLIO port on pc.por_id = port.POR_ID
    left join  
    (  
     select row_number() over (partition by emi_id order by eca_fecha_resolucion desc,eca_id desc) r,emi_id  
     ,eca_valor   
     ,cal_nombre eca_nombre  
     ,cal_nombre_personalizado eca_nombre_personalizado  
     ,eca_fecha_resolucion  
     from bvq_administracion.emisores_calificacion eca  
     join bvq_administracion.calificadoras cal on eca.cal_id=cal.cal_id  
       
     where eca_estado=21 and (eca_fecha_resolucion is null or eca_fecha_resolucion<=@i_fechaCorte)  
    ) emical on emical.emi_id=tiv_emisor and emical.r=1--(tvl_generico=1 or tiv_tipo_valor in (/*10,*/13)) and emical.emi_id=tiv_emisor and emical.r=1  
      left join BVQ_ADMINISTRACION.TIPO_VALOR_HOMOLOGADO H  
      ON PC.tvl_codigo = H.TVLH_CODIGO  
	left join BVQ_BACKOFFICE.VALOR_NOMINAL_UNITARIO VNU ON VNU.TIV_ID=pc.TIV_ID and pc.tfcorte>=VNU.VNU_FECHA_INICIO and pc.tfcorte<VNU.VNU_FECHA_FIN
  
   where sal>0  
   and  
   ISNULL(IPR_ES_CXC,0)=0  
   and  
   TIV_TIPO_RENTA=154  
   --ORDER BY TVL_CODIGO,EMS_NOMBRE,TIV_FECHA_VENCIMIENTO  
  ) s  
  --where EMISOR  ='ENERGY & PALMA ENERGY PALMA S.A.'  
  group by  TVL_NOMBRE,CUENTA_CONTABLE,VECTOR_PRECIO,TIPO,CUPON,PLAZO_PACTADO,FECHA_VENCIMIENTO_CONVENIO_PAGO,FECHA_SUSCRIPCION_CONVENIO_PAGO,FECHA_VENCIMIENTO_ORIGINAL,EMISOR,INTERVINIENTES,PRECIO_DE_HOY,VENCER,FECHA_VALOR_DE_COMPRA,YIELD,PRECIO,SECTOR,MONTO_EMITIDO,PATRIMONIO,CALIFICADORA_DE_RIESGO,CALIFICACION_DE_RIESGO,FECHA_DE_PAGO_ULTIMO_CUPON,DIAS_DE_INTERES_GANADO,PCT_A_AJUSTAR,DIAS_POR_VENCER_A_LA_COMPRA,PCT_AJUSTE_DIARIO,FACTOR_DE_AJUSTE,CONTROLADOR_SECTOR,CONTROLADOR_POSICION,PRECIO_ULTIMA_COMPRA,FECHA_ULTIMA_COMPRA,BASE_PARA_DIAS_INTERES,BASE_PARA_TASA_INTERES,VECTOR_PRECIO2,CUPON_VECTOR,CODIGO_TITULO,TIPO_VECTOR,ACCIONES_REALIZADAS,MANTIENE_VECTOR_PRECIO,ACP_ID,PROG,ACTA,GCXC_NOMBRE,TVL_CODIGO,EMS_NOMBRE,TPO_F1,OTROS_COSTOS,TPO_PROG,RECURSOS,
  TIV_VALOR_NOMINAL,ABONO_INTERES,VALNOM_ANTERIOR,FECHA_ENCARGO,DIVIDENDOS_EN_ACCIONES,ORD  ,CALIFICADORA_DE_RIESGO,CALIFICACION_DE_RIESGO,htp_numeracion  
  order by ord,tpo_f1
  
  if 1=1   
   SELECT   
   NOTA=INC_DESCRIPCION  
   FROM BVQ_BACKOFFICE.ISSPOL_NOTAS_CXC  
   WHERE @i_fechaCorte between isnull(INC_FECHA_DESDE,0) and isnull(INC_FECHA_HASTA,'9999-12-31T00:00:00')  
   AND INC_ARCHIVO='RV'  
   ORDER BY INC_ORDEN  
 end   
