CREATE VIEW BVQ_ADMINISTRACION.titulo_flujo_comun
WITH SCHEMABINDING
AS
	SELECT
		TFL_ID,
		TIV_ID,
		TFL_CODIGO,
		TFL_PERIODO,
		TFL_CAPITAL,
		TFL_FECHA_INICIO,
		TFL_INTERES,
		TFL_AMORTIZACION,
		TFL_RECUPERACION,
		TFL_FECHA_VENCIMIENTO,
		TFL_VALOR_PRESENTE,
		TFL_FECHA_INICIO_VIGENCIA,
		TFL_FECHA_FIN_VIGENCIA,
		TFL_FECHA_REGISTRO,
		TFL_FECHA_ACTUALIZACION
	FROM BVQ_ADMINISTRACION.titulo_flujo_comun_raw