--drop view _temp.GFirstOrder
alter view _temp.GUnions as
select L1Col,col,pseudo from(
values
('htp_fecha_operacion','0:htp_fecha_operacion,1:evp.fecha,2:tfcorte'),
('montooper','0:sum(montooper),1:sum(evp.montooper),2:montooper'),
('itrans','0:sum(itrans),1:sum(case when evp.es_vencimiento_interes=1 then iamortizacion end),2:sum(itrans)'),
('tpo_numeracion','0:tpo_numeracion,1:evp.tpo_numeracion,2:htp_numeracion'),
('oper','0:oper,1:oper,2:-1'),
('htp_precio_compra','0:min(evp.htp_precio_compra),1:min(tpo_precio_ingreso),2:max(precio_de_hoy)'),
('tasa_cupon','0:max(tasa_cupon),1:max(tasa_cupon),2:max(tiv_tasa_interes)'),
('liq_rendimiento','0:max(liq_rendimiento),1:max(liq_rendimiento),2:max(htp_rendimiento)'),
('valorEfectivo','0:sum(case when htp_tiene_valnom=1 or (htp_tiene_valnom=0 and htp_tpo_id<1500) then coalesce(case when tpo_numeracion in (''ATX-2025-04-24'',''ATX-2025-04-25'') then valnomCompraAnterior end,montooper)*coalesce(case when tpo_numeracion in (''ATX-2025-04-24'',''ATX-2025-04-25'') then precioCompraAnterior end,htp_precio_compra)/case when tiv_tipo_renta=153 then 100e else 1e end end),1:sum(prEfectivo*evp.htp_compra),2:valorEfectivo'),
('tiv_id','0:tpo.tiv_id,1:tpo.tiv_id,2:tiv_id'),
('fon_id','0:max(tpo.fon_id),1:max(tpo.fon_id),2:max(tpo.fon_id)'),
('esCxc','0:max(isnull(ipr_es_cxc,0)),1:convert(bit,max(isnull(convert(int,ipr_es_cxc),0))),2:max(isnull(ipr_es_cxc,0))'),
('tpo_acta','0:max(tpo.tpo_acta),1:max(tpo.tpo_acta),2:max(pc.tpo_acta)'),
('valor_pago_capital','0:null,1:sum(coalesce(case when htp_dividendo=1 or es_vencimiento_interes=1 then 0 end,case when evp.htp_tiene_valnom=0 then -specialValnom end,case when evp_abono=1 and es_vencimiento_interes=0 then vep_valor_efectivo end,capMonto,-evp.montooper)),2:null'),
('valor_pago_cupon','0:null,1:sum(evp.valor_pago_cupon),2:null'),
('Fecha_Ultimo_Pago','0:null,1:evp.fecha,2:null'),
('Saldo_Valor_Nominal','0:sum(evp.saldo),1:sum(evp.saldo),2:sum(sal)'),
('Precio_de_mercado','0:null,1:null,2:sum(precio_de_hoy)'),
('Valor_Mercado','0:null,1:null,2:Valor_Mercado'),
('TPO_MANTIENE_VECTOR_PRECIO','0:max(convert(int,tpo_mantiene_vector_precio)),1:max(convert(int,tpo_mantiene_vector_precio)),2:max(convert(int,pc.TPO_MANTIENE_VECTOR_PRECIO))'),
('evp_fecha_compra','0:htp_fecha_operacion,1:min(case when oper=0 then evp.htp_fecha_operacion end),2:min(pc.fecha_compra)'),
('dividendo_en_efectivo','0:null,1:sum(case when tiv_tipo_renta=154 and es_vencimiento_interes=1 then amount end),2:null'),
('dividendo_en_acciones','0:null,1:sum(case when tiv_tipo_renta=154 and htp_dividendo=1 then amount end),2:null'),
('opSec','0:row_number() over (partition by tpo_numeracion order by htp_fecha_operacion),1:1,2:1'),
('TPO_INTERES_TRANSCURRIDO','0:null,1:null,2:TPO_INTERES_TRANSCURRIDO'),
('TPO_COMISION_BOLSA','0:null,1:null,2:TPO_COMISION_BOLSA')
) v (col,pseudo)
left join
(values
('tiv_id','tiv.tiv_id','tiv_id'),
('TIV_CODIGO_TITULO_SIC','tiv.TIV_CODIGO_TITULO_SIC',NULL),
('htp_fecha_operacion','evp.htp_fecha_operacion','htp_fecha_operacion'),
('Interes_Acumulado','evp.itrans*errVNFactor.errVNFactor','itrans'),
('Vector_Precio','tiv_codigo_vector',NULL),
('Fecha_Vencimiento','tiv.TIV_FECHA_VENCIMIENTO',NULL),
('Fecha_Compra','evp_fecha_compra','evp_fecha_compra'),
('TIPO_ID_EMISOR','''R''',NULL),
('ID_EMISOR','iif(ems.EMS_CODIGO=''MONTECRISTI'',''0993121401001'',pju.pju_identificacion)',NULL),
('Codigo_Instrumento','bvq_administracion.GetIdentifierCode(coalesce(nullif(tiv_codigo_vector,''''),codigo_vector_original),tiv_codigo_isin)',NULL),
('Tipo_Instrumento','TVS.TVS_CODIGO',NULL),
('id_Instrumento','case bvq_administracion.GetIdentifierCode(coalesce(nullif(tiv_codigo_vector,''''),codigo_vector_original),TIV_CODIGO_ISIN) when ''07'' then rtrim(coalesce(nullif(tiv_codigo_vector,''''),codigo_vector_original))+''-''+coalesce(fixNumeracion,fon.FON_NUMERACION) when ''01'' then TIV_CODIGO_ISIN+''-''+fon.FON_NUMERACION when ''00'' then replace(fon.FON_NUMERACION,''MONTECRISTI'',''SANTACRUZ'') end',NULL),
('Bolsa_Valores','case coalesce(fon_procedencia_null,opc_procedencia) when ''G'' then ''Y'' else coalesce(fon_procedencia_null,opc_procedencia) end',NULL),
('Fecha_Emision','coalesce(tiv.TIV_FECHA_EMISION,iif(tiv.tiv_tipo_renta=154,TIV_FECHA_INSCRIPCION_SIC,null))',NULL),
('Tipo_Tasa','case when tiv.tiv_tipo_renta=153 then case when tiv.tiv_subtipo=3 then ''C'' when tiv.tiv_tipo_tasa=365 then ''F'' else ''V'' end end',NULL),
('Base_Tasa_Interes','case when tiv.tiv_tipo_renta=153 then iif(tiv.tiv_tipo_base in (354,355),1,2) end',NULL),
('Tasa_Nominal','case when tiv.tiv_tipo_renta=153 then case when tiv.tiv_tipo_tasa=365 then tiv.tiv_tasa_interes else tiv.tiv_tasa_margen + bvq_administracion.fnObtenerValorTasaPorTituloYFecha(tiv.tiv_id,evp.htp_fecha_operacion) end end',NULL),
('Valor_Nominal','evp.montooper * case when tiv.tiv_tipo_renta=154 then coalesce(VNU_VALOR,tiv.[TIV_VALOR_NOMINAL]) else 1 end *errVNFactor.errVNFactor',NULL),
('Precio_Compra','case when tiv.tiv_tipo_renta=154 then 0 else evp.htp_precio_compra end',NULL),
('Valor_Efectivo_Libros','evp.valorEfectivo*errVNFactor.errVNFactor','valorEfectivo'),
('Plazo_Inicial','convert(int,dbo.fnDias(evp.evp_fecha_compra,tiv.tiv_fecha_vencimiento,355))',NULL),
('Calificadora_Riesgo_Emision','csm.CSM_CODIGO',NULL),
('Calificacion_Riesgo_Emision','coalesce(emscal.[ENC_VALOR],eca_valor,[TCA_VALOR],''NO DISPONIBLE'')',NULL),
('Fecha_Ultima_Calificacion','coalesce(emscal.ENC_FECHA_DESDE,tcacal.TCA_FECHA_DESDE,emical.eca_fecha_resolucion)',NULL),
('Numero_Acciones','case when tiv.tiv_tipo_renta=154 and TVL_CODIGO not in (''ENC'') then evp.montooper end',NULL),
('Valor_Accion','case when tiv.tiv_tipo_renta=154 and TVL_CODIGO not in (''ENC'') then coalesce(VNU_VALOR,tiv.[TIV_VALOR_NOMINAL]) end',NULL),
('Precio_Mercado','case when oper=-1 then precio_de_mercado else (select top 1 precio_de_mercado from BVQ_BACKOFFICE.VALORACION_SB v where v.tpo_numeracion=evp.tpo_numeracion and v.htp_fecha_operacion=evp.htp_fecha_operacion) end',NULL),
('Valor_Mercado','case when oper=-1 then Valor_Mercado else (select top 1 Valor_Mercado from BVQ_BACKOFFICE.VALORACION_SB v where v.tpo_numeracion=evp.tpo_numeracion and v.htp_fecha_operacion=evp.htp_fecha_operacion) end*errVNFactor.errVNFactor','Valor_Mercado'),
('Fecha_Precio_Mercado','evp.htp_fecha_operacion',NULL),
('Fondo_Inversion','null',NULL),
('Periodo_Amortizacion_codigo','p.codigo',NULL),
('Periodo_Amortizacion','p.nombre',NULL),
('Periodicidad_Cupon_codigo','p.codigo',NULL),
('Periodicidad_Cupon','p.nombre',NULL),
('Casa_de_Valores_codigo','coalesce(CVA_CODIGO_SB_DIRECTO,CVA_CODIGO_SB)',NULL),
('Casa_Valores','opc.PJU_RAZON_SOCIAL',NULL),
('Tipo_Id_Custodio','coalesce(case opc_Via when 0 then ''R'' when 1 then ''R'' end, case tiv.tiv_camara when ''Decevale'' then ''R'' when ''DCV-BCE'' then ''R'' when ''DCV'' then ''R'' end)',NULL),
('numero_resolucion','FON_NUMERO_RESOLUCION',NULL),
('Resolucion_Decreto','case when tiv.tiv_tipo_valor=3 then evp.tpo_acta else tiv_numero_supercias end',NULL),
('Nro_de_Inscripcion_Decreto','null',NULL),
('Inscripcion_CPMV','tiv_numero_rmv',NULL),
('Id_Custodio','isnull(case opc_Via when 0 then ''0991283765001'' when 1 then ''1760002600001'' end, case tiv.tiv_camara when ''Decevale'' then ''0991283765001'' when ''DCV-BCE'' then ''1760002600001'' when ''DCV'' then ''1760002600001'' end)',NULL),
('Numero_liquidacion','fon.FON_NUMERO_LIQUIDACION',NULL),
('Tipo_transaccion','case oper when 0 then ''L'' when 1 then ''P'' when -1 then ''V'' end',NULL),
('Fecha_transaccion','htp_fecha_operacion',NULL),
('Dias_transcurridos','dbo.fnDias(tfl.TFL_FECHA_INICIO, evp.htp_fecha_operacion,tiv.TIV_TIPO_BASE)',NULL),
('Dias_por_vencer','dbo.fnDias(evp.htp_fecha_operacion,tfl.TFL_FECHA_VENCIMIENTO,tiv.TIV_TIPO_BASE)',NULL),
('Fuente_Cotizacion','''Q''',NULL),
('Yield','liq_rendimiento','liq_rendimiento'),
('oper','oper','oper'),
('esCxc','esCxc','esCxc'),
('valor_pago_capital','valor_pago_capital*errVNFactor.errVNFactor','valor_pago_capital'),
('valor_pago_cupon','valor_pago_cupon*errVNFactor.errVNFactor','valor_pago_cupon'),
('Fecha_Ultimo_Pago','Fecha_Ultimo_Pago','Fecha_Ultimo_Pago'),
('Saldo_Valor_Nominal','Saldo_Valor_Nominal*errVNFactor.errVNFactor','Saldo_Valor_Nominal'),
('tiv_tipo_renta','tiv.tiv_tipo_renta',NULL),
('Pago_dividendo_en_acciones','dividendo_en_acciones',NULL),
('Pago_dividendo_efectivo','dividendo_en_efectivo',NULL),
('FON_ID','evp.FON_ID',NULL),
('EMS_NOMBRE','iif(ems.EMS_CODIGO=''MONTECRISTI'',''FIDEICOMISO SANTA CRUZ'',ems.EMS_NOMBRE)',NULL),
('EMS_CODIGO','ems.EMS_CODIGO',NULL),
('TVS_DESCRIPCION','TVS.TVS_DESCRIPCION',NULL),
('CVA_SIGLAS','opc.CVA_SIGLAS',NULL),
('OPC_VIA','OPC_VIA',NULL),
('OPC_NUM_OPE','OPC_NUM_OPE',NULL),
('TPO_INTERES_TRANSCURRIDO','TPO_INTERES_TRANSCURRIDO','TPO_INTERES_TRANSCURRIDO'),
('TPO_COMISION_BOLSA','TPO_COMISION_BOLSA','TPO_COMISION_BOLSA'),
('INTERES_GANADO_2','INTERES_GANADO_2*errVNFactor.errVNFactor',NULL),
('tiv_tipo_base','tiv.tiv_tipo_base',NULL),
('tvl_descripcion','tvl.tvl_descripcion',NULL),
('INTERES_GANADO','itrans*errVNFactor.errVNFactor',NULL),
('Fecha_Ultimo_Pago_Capital','tfl.TFL_FECHA_INICIO',NULL)
) level1(L1Col,expr,UCol)
on col=UCol

