create view BVQ_ADMINISTRACION.SB_CALIFICACIONES as
	select codigo,sandp,moodys,fitch from
	(
	VALUES
	 (30, 'No disponible', 'No disponible', 'No disponible')
	,(25, 'E',   'E',    'E')
	,(24, 'AAA+', 'Aaa1', 'AAA+')
	,(22, 'AAA-', 'Aaa3', 'AAA-')
	,(21, 'AAA', 'Aaa2', 'AAA')
	,(20, 'AA+', 'Aa1',  'AA+')
	,(19, 'AA',  'Aa2',  'AA')
	,(18, 'AA-', 'Aa3',  'AA-')
	,(17, 'A+',  'A1',   'A+')
	,(16, 'A',   'A2',   'A')
	,(15, 'A-',  'A3',   'A-')
	,(14, 'BBB+', 'Baa1', 'BBB+')
	,(13, 'BBB',  'Baa2', 'BBB')
	,(12, 'BBB-', 'Baa3', 'BBB-')
	,(11, 'BB+',  'Ba1',  'BB+')
	,(10, 'BB',   'Ba2',  'BB')
	,(9,  'BB-',  'Ba3',  'BB-')
	,(8,  'B+',   'B1',   'B+')
	,(7,  'B',    'B2',   'B')
	,(6,  'B-',   'B3',   'B-')
	,(5,  'CCC+', 'Caa1', 'CCC+')
	,(4,  'CCC',  'Caa2', 'CCC')
	,(3,  'CCC-', 'Caa3', 'CCC-')
	,(2,  'CC',   'Ca',   'CC')
	,(1,  'C',    'C',    'C')
	,(0,  'D',    'D',    'D')
	) v(codigo,sandp,moodys,fitch)
