CREATE FUNCTION [BVQ_BACKOFFICE].[tfObtenerActivosInmobiliariosISSPOL](@i_fecha_corte DATE) RETURNS TABLE AS
RETURN (
SELECT
	IMB.[IMB_ID]
   ,[POR_CODIGO]
   ,[IMB_TIPO]
   ,[IMB_PROVINCIA]
   ,[IMB_UBICACION]
   ,IMB_VALOR_LIBROS = IMB_VALOR_LIBROS + ISNULL(SUM(HAI_VALOR), 0)
   ,[IMB_VALOR_AVALUO] = COALESCE(AAI_VALOR, IMB_VALOR_AVALUO)
   ,[IMB_FECHA_ULT_AVALUO] = COALESCE(AAI_FECHA, IMB_FECHA_ULT_AVALUO)
   ,[IMB_FECHA_ESCRITURA]
   ,[IMB_CUENTA_CONTABLE]
   ,[IMB_FORMA_ADQUISICION]
FROM [BVQ_BACKOFFICE].[ACTIVOS_INMOBILIARIOS] IMB
LEFT JOIN BVQ_BACKOFFICE.HISTORICO_ACTIVOS_INMOBILIARIOS HAI
	ON HAI.IMB_ID = IMB.IMB_ID
	AND HAI_FECHA <= @i_fecha_corte
LEFT JOIN (SELECT
		ROW_NUMBER() OVER (PARTITION BY imb_id ORDER BY AAI_FECHA DESC, aai_id DESC) r
	   ,AAI_VALOR
	   ,AAI_FECHA
	   ,IMB_ID
	FROM BVQ_BACKOFFICE.AVALUO_ACTIVOS_INMOBILIARIOS
	WHERE AAI_FECHA <= @i_fecha_corte) AAI
	ON AAI.IMB_ID = IMB.IMB_ID
	AND r = 1
GROUP BY IMB.[IMB_ID]
		,[POR_CODIGO]
		,[IMB_TIPO]
		,[IMB_PROVINCIA]
		,[IMB_UBICACION]
		,[IMB_VALOR_LIBROS]
		,[IMB_VALOR_AVALUO]
		,[IMB_FECHA_ULT_AVALUO]
		,[IMB_FECHA_ESCRITURA]
		,[IMB_CUENTA_CONTABLE]
		,[IMB_FORMA_ADQUISICION]
		,AAI_VALOR
		,AAI_FECHA
HAVING IMB_VALOR_LIBROS + ISNULL(SUM(HAI_VALOR), 0) > 0
)