create view BVQ_ADMINISTRACION.TipoValorSBMap as
	select codigo,descr,tipren,TVL_NOMBRE from(
	VALUES
	-- FIJA
	(1,  'Certificado de Depósito',                    'FIJA',     'CERTIFICADO DE DEPÓSITO'),
	(2,  'Certificado de Inversión',                   'FIJA',     'CERTIFICADO DE INVERSIÓN'),
	(3,  'Póliza de Acumulación',                      'FIJA',     'PÓLIZA DE ACUMULACIÓN'),
	(4,  'Bonos de Estado',                            'FIJA',     'BONOS DEL ESTADO'),
	(5,  'Certificados de Tesorería',                  'FIJA',     'CERTIFICADO DE TESORERÍA'),
	(5,  'Certificados de Tesorería',                  'FIJA',     'NOTAS DEL TESORO'),
	(6,  'Obligaciones',                              'FIJA',     'OBLIGACIONES'),
	(7,  'Obligaciones convertibles en acciones',      'FIJA',     'OBLIGACIONES CONVERTIBLES EN ACCIONES'),
	(8,  'Papel Comercial',                            'FIJA',     'PAPEL COMERCIAL'),
	(9,  'Facturas Comerciales Negociables',           'FIJA',     'FACTURA COMERCIAL'),
	(10, 'Valores de Titularización de Cartera',       'FIJA',     'VALORES DE CONTENIDO CREDITICIO'),
	(11, 'Dinero efectivo exterior',                   'FIJA',     NULL),
	(12, 'Bono exterior',                              'FIJA',     NULL),
	(13, 'Reporto Bursátil',                           'FIJA',     'REPORTO'),
	(13, 'Reporto Bursátil',                           'FIJA',     'PACTO DE RECOMPRA'),
	(14, 'Inversiones Exterior RF',                    'FIJA',     NULL),
	(15, 'Overnight',                                  'FIJA',     NULL),
	(16, 'Pagaré',                                    'FIJA',     'PAGARÉ'),
	(16, 'Pagaré',                                    'FIJA',     'PAGARÉ - REVNI'),
	(17, 'Letra de cambio',                            'FIJA',     'LETRA DE CAMBIO'),
	(18, 'Cupones',                                   'FIJA',     'CUPÓN DE INTERÉS'),
	(18, 'Cupones',                                   'FIJA',     'CUPÓN DE CAPITAL'),
	(18, 'Cupones',                                   'FIJA',     'CUPÓN INTERÉS Y CAPITAL'),
	(19, 'Cédulas Hipotecarias',                       'FIJA',     'CEDULAS HIPOTECARIAS'),
	(20, 'Acciones',                                  'VARIABLE', 'ACCIONES'),
	(20, 'Acciones',                                  'VARIABLE', 'ACCIONES REVNI'),
	(21, 'Valor Patrimonial Proporcional',            'VARIABLE', NULL),
	(22, 'Valores de Titularización de Participación', 'VARIABLE', 'VALORES DE TITULARIZACIÓN DE PARTICIPACIÓN'),
	(22, 'Valores de Titularización de Participación', 'VARIABLE', 'CUOTAS DE PARTICIPACIÓN'),
	(23, 'Encargo Fiduciario',                         'VARIABLE', 'ENCARGO DE DERECHOS FIDUCIARIOS'),
	(23, 'Encargo Fiduciario',                         'VARIABLE', 'CESIÓN DE DERECHOS FIDUCIARIOS'),
	(24, 'Fondos de Inversión',                        'VARIABLE', 'FONDO DE INVERSIÓN'),
	(25, 'Fideicomisos',                              'VARIABLE', NULL),
	(26, 'Acciones exterior',                         'VARIABLE', NULL),
	(27, 'Inversiones Exterior RV',                    'VARIABLE', NULL)
	) SbTipos(codigo,descr,tipren,TVL_NOMBRE)
