-- =============================================
-- Inserta Módulo Créditos solo si no existe
-- =============================================
IF NOT EXISTS (
    SELECT 1
    FROM BVQ_SEGURIDAD.MODULO
    WHERE MOD_ID = 6
)
BEGIN
    INSERT INTO BVQ_SEGURIDAD.MODULO
        (MOD_ID, MOD_DESCRIPCION, MOD_NOMBRE, MOD_CODIGO, MOD_ESTADO)
    VALUES
        (6, N'Módulo Créditos', N'Créditos', 'CRED', 'A');
END

-- =============================================
-- Inserta Funcionalidades del Módulo Créditos
-- (IDs calculados dinámicamente desde MAX(FUN_ID) + 1)
-- =============================================

DECLARE @NextId       INT;
DECLARE @IdCreditos   INT;
DECLARE @IdCartera    INT;
DECLARE @IdTasaProm   INT;
DECLARE @IdTasaMora   INT;
DECLARE @IdTIR        INT;
DECLARE @IdFlujoCaja  INT;
DECLARE @IdPivot      INT;

SET @NextId = ISNULL((SELECT MAX(FUN_ID) FROM BVQ_SEGURIDAD.FUNCIONALIDAD), 0) + 1;

-- Créditos (nodo padre)
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.FUNCIONALIDAD WHERE FUN_CODIGO = 'CREDITOS_ISSPOL')
BEGIN
    SET @IdCreditos = @NextId;

    INSERT INTO BVQ_SEGURIDAD.FUNCIONALIDAD
        (FUN_ID, MOD_ID, FUN_NOMBRE, FUN_TIPO, FUN_CODIGO, FUN_ESTADO,
         FUN_NOMBRE_DLL, FUN_NOMBRE_CLASE, FUN_PADRE, FUN_AUDITAR, FUN_ORDEN, FUN_ES_VERSION2)
    VALUES
        (@IdCreditos, 6, N'Créditos', 88, 'CREDITOS_ISSPOL', 82,
         NULL, NULL, NULL, 1, 86, NULL);

    SET @NextId = @NextId + 1;
END
ELSE
BEGIN
    SET @IdCreditos = (SELECT FUN_ID FROM BVQ_SEGURIDAD.FUNCIONALIDAD WHERE FUN_CODIGO = 'CREDITOS_ISSPOL');
END

-- Cartera de créditos
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.FUNCIONALIDAD WHERE FUN_CODIGO = 'CRED_CARTERA')
BEGIN
    SET @IdCartera = @NextId;

    INSERT INTO BVQ_SEGURIDAD.FUNCIONALIDAD
        (FUN_ID, MOD_ID, FUN_NOMBRE, FUN_TIPO, FUN_CODIGO, FUN_ESTADO,
         FUN_NOMBRE_DLL, FUN_NOMBRE_CLASE, FUN_PADRE, FUN_AUDITAR, FUN_ORDEN, FUN_ES_VERSION2)
    VALUES
        (@IdCartera, 6, N'Cartera de créditos', 89, 'CRED_CARTERA', 82,
         'Bvq.Sipla.Portfolio.Module.dll', 'Bvq.Sipla.Portfolio.Module.CarteraCreditosView', @IdCreditos, 1, 1, NULL);

    SET @NextId = @NextId + 1;
END
ELSE
BEGIN
    SET @IdCartera = (SELECT FUN_ID FROM BVQ_SEGURIDAD.FUNCIONALIDAD WHERE FUN_CODIGO = 'CRED_CARTERA');
END

-- Tasa promedio ponderada
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.FUNCIONALIDAD WHERE FUN_CODIGO = 'CRED_TASA_PROMEDIO')
BEGIN
    SET @IdTasaProm = @NextId;

    INSERT INTO BVQ_SEGURIDAD.FUNCIONALIDAD
        (FUN_ID, MOD_ID, FUN_NOMBRE, FUN_TIPO, FUN_CODIGO, FUN_ESTADO,
         FUN_NOMBRE_DLL, FUN_NOMBRE_CLASE, FUN_PADRE, FUN_AUDITAR, FUN_ORDEN, FUN_ES_VERSION2)
    VALUES
        (@IdTasaProm, 6, N'Tasa promedio ponderada', 89, 'CRED_TASA_PROMEDIO', 82,
         'Bvq.Sipla.Portfolio.Module.dll', 'Bvq.Sipla.Portfolio.Module.TasaPromedioPonderadaView', @IdCreditos, 1, 1, NULL);

    SET @NextId = @NextId + 1;
END
ELSE
BEGIN
    SET @IdTasaProm = (SELECT FUN_ID FROM BVQ_SEGURIDAD.FUNCIONALIDAD WHERE FUN_CODIGO = 'CRED_TASA_PROMEDIO');
END

-- Tasa de mora
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.FUNCIONALIDAD WHERE FUN_CODIGO = 'CRED_TASA_MORA')
BEGIN
    SET @IdTasaMora = @NextId;

    INSERT INTO BVQ_SEGURIDAD.FUNCIONALIDAD
        (FUN_ID, MOD_ID, FUN_NOMBRE, FUN_TIPO, FUN_CODIGO, FUN_ESTADO,
         FUN_NOMBRE_DLL, FUN_NOMBRE_CLASE, FUN_PADRE, FUN_AUDITAR, FUN_ORDEN, FUN_ES_VERSION2)
    VALUES
        (@IdTasaMora, 6, N'Tasa de mora', 89, 'CRED_TASA_MORA', 82,
         'Bvq.Sipla.Portfolio.Module.dll', 'Bvq.Sipla.Portfolio.Module.TasaMoraView', @IdCreditos, 1, 1, NULL);

    SET @NextId = @NextId + 1;
END
ELSE
BEGIN
    SET @IdTasaMora = (SELECT FUN_ID FROM BVQ_SEGURIDAD.FUNCIONALIDAD WHERE FUN_CODIGO = 'CRED_TASA_MORA');
END

-- Tasa interna de retorno
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.FUNCIONALIDAD WHERE FUN_CODIGO = 'CRED_TIR')
BEGIN
    SET @IdTIR = @NextId;

    INSERT INTO BVQ_SEGURIDAD.FUNCIONALIDAD
        (FUN_ID, MOD_ID, FUN_NOMBRE, FUN_TIPO, FUN_CODIGO, FUN_ESTADO,
         FUN_NOMBRE_DLL, FUN_NOMBRE_CLASE, FUN_PADRE, FUN_AUDITAR, FUN_ORDEN, FUN_ES_VERSION2)
    VALUES
        (@IdTIR, 6, N'Tasa interna de retorno', 89, 'CRED_TIR', 82,
         NULL, NULL, @IdCreditos, 1, 1, NULL);

    SET @NextId = @NextId + 1;
END
ELSE
BEGIN
    SET @IdTIR = (SELECT FUN_ID FROM BVQ_SEGURIDAD.FUNCIONALIDAD WHERE FUN_CODIGO = 'CRED_TIR');
END

-- Flujo de Caja
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.FUNCIONALIDAD WHERE FUN_CODIGO = 'CRED_FLUJO')
BEGIN
    SET @IdFlujoCaja = @NextId;

    INSERT INTO BVQ_SEGURIDAD.FUNCIONALIDAD
        (FUN_ID, MOD_ID, FUN_NOMBRE, FUN_TIPO, FUN_CODIGO, FUN_ESTADO,
         FUN_NOMBRE_DLL, FUN_NOMBRE_CLASE, FUN_PADRE, FUN_AUDITAR, FUN_ORDEN, FUN_ES_VERSION2)
    VALUES
        (@IdFlujoCaja, 6, N'Flujo de Caja', 89, 'CRED_FLUJO', 82,
         'Bvq.Sipla.Portfolio.Module.dll', 'Bvq.Sipla.Portfolio.Module.CashFlowReportView', @IdCreditos, 1, 1, NULL);

    SET @NextId = @NextId + 1;
END
ELSE
BEGIN
    SET @IdFlujoCaja = (SELECT FUN_ID FROM BVQ_SEGURIDAD.FUNCIONALIDAD WHERE FUN_CODIGO = 'CRED_FLUJO');
END

-- Pivot
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.FUNCIONALIDAD WHERE FUN_CODIGO = 'CRED_PIVOT')
BEGIN
    SET @IdPivot = @NextId;

    INSERT INTO BVQ_SEGURIDAD.FUNCIONALIDAD
        (FUN_ID, MOD_ID, FUN_NOMBRE, FUN_TIPO, FUN_CODIGO, FUN_ESTADO,
         FUN_NOMBRE_DLL, FUN_NOMBRE_CLASE, FUN_PADRE, FUN_AUDITAR, FUN_ORDEN, FUN_ES_VERSION2)
    VALUES
        (@IdPivot, 6, N'Pivot', 89, 'CRED_PIVOT', 82,
         'bvq.sipla.portfolio.module.dll', 'Bvq.Sipla.Portfolio.Module.RentaVariablePivotReportView', @IdCreditos, 1, 1, NULL);

    SET @NextId = @NextId + 1;
END
ELSE
BEGIN
    SET @IdPivot = (SELECT FUN_ID FROM BVQ_SEGURIDAD.FUNCIONALIDAD WHERE FUN_CODIGO = 'CRED_PIVOT');
END

-- =============================================
-- Inserta Perfil-Funcionalidad (Perfil 41 → Funcionalidades de Créditos)
-- (usa los IDs recién generados o los existentes)
-- =============================================

-- Perfil 41 / Créditos
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD WHERE PRF_ID = 41 AND FUN_ID = @IdCreditos)
BEGIN
    INSERT INTO BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD (PRF_ID, FUN_ID)
    VALUES (41, @IdCreditos);
END

-- Perfil 41 / Cartera de créditos
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD WHERE PRF_ID = 41 AND FUN_ID = @IdCartera)
BEGIN
    INSERT INTO BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD (PRF_ID, FUN_ID)
    VALUES (41, @IdCartera);
END

-- Perfil 41 / Tasa promedio ponderada
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD WHERE PRF_ID = 41 AND FUN_ID = @IdTasaProm)
BEGIN
    INSERT INTO BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD (PRF_ID, FUN_ID)
    VALUES (41, @IdTasaProm);
END

-- Perfil 41 / Tasa de mora
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD WHERE PRF_ID = 41 AND FUN_ID = @IdTasaMora)
BEGIN
    INSERT INTO BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD (PRF_ID, FUN_ID)
    VALUES (41, @IdTasaMora);
END

-- Perfil 41 / Tasa interna de retorno
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD WHERE PRF_ID = 41 AND FUN_ID = @IdTIR)
BEGIN
    INSERT INTO BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD (PRF_ID, FUN_ID)
    VALUES (41, @IdTIR);
END

-- Perfil 41 / Flujo de Caja
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD WHERE PRF_ID = 41 AND FUN_ID = @IdFlujoCaja)
BEGIN
    INSERT INTO BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD (PRF_ID, FUN_ID)
    VALUES (41, @IdFlujoCaja);
END

-- Perfil 41 / Pivot
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD WHERE PRF_ID = 41 AND FUN_ID = @IdPivot)
BEGIN
    INSERT INTO BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD (PRF_ID, FUN_ID)
    VALUES (41, @IdPivot);
END