-- =============================================
-- Inserta Módulo Créditos solo si no existe
-- =============================================
IF NOT EXISTS (
    SELECT 1
    FROM BVQ_SEGURIDAD.MODULO
    WHERE MOD_ID = 6
)
BEGIN
    INSERT INTO BVQ_SEGURIDAD.MODULO
        (MOD_ID, MOD_DESCRIPCION, MOD_NOMBRE, MOD_CODIGO, MOD_ESTADO)
    VALUES
        (6, N'Módulo Créditos', N'Créditos', 'CRED', 'A');
END

-- =============================================
-- Inserta Funcionalidades del Módulo Créditos
-- =============================================

-- FUN_ID = 294 — Créditos (nodo padre)
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.FUNCIONALIDAD WHERE FUN_ID = 294)
BEGIN
    INSERT INTO BVQ_SEGURIDAD.FUNCIONALIDAD
        (FUN_ID, MOD_ID, FUN_NOMBRE, FUN_TIPO, FUN_CODIGO, FUN_ESTADO,
         FUN_NOMBRE_DLL, FUN_NOMBRE_CLASE, FUN_PADRE, FUN_AUDITAR, FUN_ORDEN, FUN_ES_VERSION2)
    VALUES
        (294, 6, N'Créditos', 88, 'CREDITOS_ISSPOL', 82,
         NULL, NULL, NULL, 1, 86, NULL);
END

-- FUN_ID = 295 — Cartera de créditos
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.FUNCIONALIDAD WHERE FUN_ID = 295)
BEGIN
    INSERT INTO BVQ_SEGURIDAD.FUNCIONALIDAD
        (FUN_ID, MOD_ID, FUN_NOMBRE, FUN_TIPO, FUN_CODIGO, FUN_ESTADO,
         FUN_NOMBRE_DLL, FUN_NOMBRE_CLASE, FUN_PADRE, FUN_AUDITAR, FUN_ORDEN, FUN_ES_VERSION2)
    VALUES
        (295, 6, N'Cartera de créditos', 89, 'CRED_CARTERA', 82,
         NULL, NULL, 294, 1, 1, NULL);
END

-- FUN_ID = 296 — Tasa promedio ponderada
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.FUNCIONALIDAD WHERE FUN_ID = 296)
BEGIN
    INSERT INTO BVQ_SEGURIDAD.FUNCIONALIDAD
        (FUN_ID, MOD_ID, FUN_NOMBRE, FUN_TIPO, FUN_CODIGO, FUN_ESTADO,
         FUN_NOMBRE_DLL, FUN_NOMBRE_CLASE, FUN_PADRE, FUN_AUDITAR, FUN_ORDEN, FUN_ES_VERSION2)
    VALUES
        (296, 6, N'Tasa promedio ponderada', 89, 'CRED_TASA_PROMEDIO', 82,
         'Bvq.Sipla.Portfolio.Module.dll', 'Bvq.Sipla.Portfolio.Module.TasaPromedioPonderadaView', 294, 1, 1, NULL);
END

-- FUN_ID = 297 — Tasa de mora
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.FUNCIONALIDAD WHERE FUN_ID = 297)
BEGIN
    INSERT INTO BVQ_SEGURIDAD.FUNCIONALIDAD
        (FUN_ID, MOD_ID, FUN_NOMBRE, FUN_TIPO, FUN_CODIGO, FUN_ESTADO,
         FUN_NOMBRE_DLL, FUN_NOMBRE_CLASE, FUN_PADRE, FUN_AUDITAR, FUN_ORDEN, FUN_ES_VERSION2)
    VALUES
        (297, 6, N'Tasa de mora', 89, 'CRED_TASA_MORA', 82,
         NULL, NULL, 294, 1, 1, NULL);
END

-- FUN_ID = 298 — Tasa interna de retorno
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.FUNCIONALIDAD WHERE FUN_ID = 298)
BEGIN
    INSERT INTO BVQ_SEGURIDAD.FUNCIONALIDAD
        (FUN_ID, MOD_ID, FUN_NOMBRE, FUN_TIPO, FUN_CODIGO, FUN_ESTADO,
         FUN_NOMBRE_DLL, FUN_NOMBRE_CLASE, FUN_PADRE, FUN_AUDITAR, FUN_ORDEN, FUN_ES_VERSION2)
    VALUES
        (298, 6, N'Tasa interna de retorno', 89, 'CRED_TIR', 82,
         NULL, NULL, 294, 1, 1, NULL);
END

-- FUN_ID = 299 — Flujo de Caja
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.FUNCIONALIDAD WHERE FUN_ID = 299)
BEGIN
    INSERT INTO BVQ_SEGURIDAD.FUNCIONALIDAD
        (FUN_ID, MOD_ID, FUN_NOMBRE, FUN_TIPO, FUN_CODIGO, FUN_ESTADO,
         FUN_NOMBRE_DLL, FUN_NOMBRE_CLASE, FUN_PADRE, FUN_AUDITAR, FUN_ORDEN, FUN_ES_VERSION2)
    VALUES
        (299, 6, N'Flujo de Caja', 89, 'IISPOL_CASH_FLOW', 82,
         'Bvq.Sipla.Portfolio.Module.dll', 'Bvq.Sipla.Portfolio.Module.CashFlowReportView', 294, 1, 1, NULL);
END

-- FUN_ID = 300 — Pivot
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.FUNCIONALIDAD WHERE FUN_ID = 300)
BEGIN
    INSERT INTO BVQ_SEGURIDAD.FUNCIONALIDAD
        (FUN_ID, MOD_ID, FUN_NOMBRE, FUN_TIPO, FUN_CODIGO, FUN_ESTADO,
         FUN_NOMBRE_DLL, FUN_NOMBRE_CLASE, FUN_PADRE, FUN_AUDITAR, FUN_ORDEN, FUN_ES_VERSION2)
    VALUES
        (300, 6, N'Pivot', 89, 'BCK_POR_PIVOT', 82,
         'bvq.sipla.portfolio.module.dll', 'Bvq.Sipla.Portfolio.Module.RentaVariablePivotReportView', 294, 1, 1, NULL);
END

-- =============================================
-- Inserta Perfil-Funcionalidad (Perfil 41 → Funcionalidades de Créditos)
-- =============================================

-- Perfil 41 / Créditos (294)
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD WHERE PRF_ID = 41 AND FUN_ID = 294)
BEGIN
    INSERT INTO BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD (PRF_ID, FUN_ID)
    VALUES (41, 294);
END

-- Perfil 41 / Cartera de créditos (295)
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD WHERE PRF_ID = 41 AND FUN_ID = 295)
BEGIN
    INSERT INTO BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD (PRF_ID, FUN_ID)
    VALUES (41, 295);
END

-- Perfil 41 / Tasa promedio ponderada (296)
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD WHERE PRF_ID = 41 AND FUN_ID = 296)
BEGIN
    INSERT INTO BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD (PRF_ID, FUN_ID)
    VALUES (41, 296);
END

-- Perfil 41 / Tasa de mora (297)
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD WHERE PRF_ID = 41 AND FUN_ID = 297)
BEGIN
    INSERT INTO BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD (PRF_ID, FUN_ID)
    VALUES (41, 297);
END

-- Perfil 41 / Tasa interna de retorno (298)
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD WHERE PRF_ID = 41 AND FUN_ID = 298)
BEGIN
    INSERT INTO BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD (PRF_ID, FUN_ID)
    VALUES (41, 298);
END

-- Perfil 41 / Flujo de Caja (299)
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD WHERE PRF_ID = 41 AND FUN_ID = 299)
BEGIN
    INSERT INTO BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD (PRF_ID, FUN_ID)
    VALUES (41, 299);
END

-- Perfil 41 / Pivot (300)
IF NOT EXISTS (SELECT 1 FROM BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD WHERE PRF_ID = 41 AND FUN_ID = 300)
BEGIN
    INSERT INTO BVQ_SEGURIDAD.PERFIL_FUNCIONALIDAD (PRF_ID, FUN_ID)
    VALUES (41, 300);
END