if object_id('bvq_administracion.cambio_de_patrimonio_retrasado') is null
begin
	CREATE TABLE [BVQ_ADMINISTRACION].[CAMBIO_DE_PATRIMONIO_RETRASADO](
		[CPR_ID] [int] IDENTITY(1,1) NOT NULL,
		[EMS_ID] [int] NULL,
		[CPR_FECHA_DESDE_REAL] [date] NOT NULL,
		[CPR_FECHA_REPORTE] [date] NOT NULL,
		[CPR_VALOR] [float] NOT NULL,
	PRIMARY KEY CLUSTERED 
	(
		[CPR_ID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]

	ALTER TABLE [BVQ_ADMINISTRACION].[CAMBIO_DE_PATRIMONIO_RETRASADO]  WITH CHECK ADD FOREIGN KEY([EMS_ID])
	REFERENCES [BVQ_ADMINISTRACION].[EMISOR] ([EMS_ID])
end

