IF not EXISTS(SELECT 1 FROM sys.columns 
          WHERE Name = N'POR_SIGLAS'
          AND Object_ID = Object_ID(N'BVQ_BACKOFFICE.PORTAFOLIO'))
BEGIN
    alter table BVQ_BACKOFFICE.PORTAFOLIO 
   add POR_SIGLAS varchar(50) 
END
GO

UPDATE BVQ_BACKOFFICE.PORTAFOLIO SET POR_SIGLAS = 'ACP' WHERE POR_CODIGO = 'Accidentes profesionales'
GO
UPDATE BVQ_BACKOFFICE.PORTAFOLIO SET POR_SIGLAS = 'SVA' WHERE POR_CODIGO = 'Seguro de vida activos'
GO
UPDATE BVQ_BACKOFFICE.PORTAFOLIO SET POR_SIGLAS = 'MOR' WHERE POR_CODIGO = 'Mortuoria'
GO
UPDATE BVQ_BACKOFFICE.PORTAFOLIO SET POR_SIGLAS = 'FR' WHERE POR_CODIGO = 'Fondos de reserva'
GO
UPDATE BVQ_BACKOFFICE.PORTAFOLIO SET POR_SIGLAS = 'SEM' WHERE POR_CODIGO = 'Enfermedad y maternidad'
GO
UPDATE BVQ_BACKOFFICE.PORTAFOLIO SET POR_SIGLAS = 'FV' WHERE POR_CODIGO = 'Fondo de vivienda'
GO
UPDATE BVQ_BACKOFFICE.PORTAFOLIO SET POR_SIGLAS = 'SS' WHERE POR_CODIGO = 'Seguro de saldos'
GO
UPDATE BVQ_BACKOFFICE.PORTAFOLIO SET POR_SIGLAS = 'SD' WHERE POR_CODIGO = 'Seguro de desgravamen'
GO
UPDATE BVQ_BACKOFFICE.PORTAFOLIO SET POR_SIGLAS = 'SVC' WHERE POR_CODIGO = 'Seguro de vida contratado'
GO
UPDATE BVQ_BACKOFFICE.PORTAFOLIO SET POR_SIGLAS = 'IP' WHERE POR_CODIGO = 'Ind,profesional'
GO
UPDATE BVQ_BACKOFFICE.PORTAFOLIO SET POR_SIGLAS = 'CS' WHERE POR_CODIGO = 'Cesantía'
GO
UPDATE BVQ_BACKOFFICE.PORTAFOLIO SET POR_SIGLAS = 'RM' WHERE POR_CODIGO = 'RIM-Mortuoria NR'
GO
UPDATE BVQ_BACKOFFICE.PORTAFOLIO SET POR_SIGLAS = 'SGV' WHERE POR_CODIGO = 'Vida-acc. profesionales NR'
GO
