IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('BVQ_BACKOFFICE.CREDITO_CARTERA_CUOTA') AND name = 'tasa')
    ALTER TABLE [BVQ_BACKOFFICE].[CREDITO_CARTERA_CUOTA] ADD tasa float;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('BVQ_BACKOFFICE.CREDITO_CARTERA_CUOTA') AND name = 'abono')
    ALTER TABLE [BVQ_BACKOFFICE].[CREDITO_CARTERA_CUOTA] ADD abono money;