IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('BVQ_BACKOFFICE.CREDITO_CARTERA_CUOTA') AND name = 'producto')
    ALTER TABLE [BVQ_BACKOFFICE].[CREDITO_CARTERA_CUOTA] ADD [producto] [varchar](200) NULL;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('BVQ_BACKOFFICE.CREDITO_CARTERA_CUOTA') AND name = 'segmento')
    ALTER TABLE [BVQ_BACKOFFICE].[CREDITO_CARTERA_CUOTA] ADD [segmento] [varchar](200) NULL;
