IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('BVQ_BACKOFFICE.CREDITO_CARTERA_CUOTA') AND name = 'pagada')
    ALTER TABLE [BVQ_BACKOFFICE].[CREDITO_CARTERA_CUOTA] ADD [pagada] [bit] NOT NULL DEFAULT 0;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('BVQ_BACKOFFICE.CREDITO_CARTERA_CUOTA') AND name = 'id_rubro')
    ALTER TABLE [BVQ_BACKOFFICE].[CREDITO_CARTERA_CUOTA] ADD [id_rubro] [varchar](3) NULL;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('BVQ_BACKOFFICE.CREDITO_CARTERA_CUOTA') AND name = 'saldo')
    ALTER TABLE [BVQ_BACKOFFICE].[CREDITO_CARTERA_CUOTA] ADD [saldo] [money] NULL;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('BVQ_BACKOFFICE.CREDITO_CARTERA_CUOTA') AND name = 'estado')
    ALTER TABLE [BVQ_BACKOFFICE].[CREDITO_CARTERA_CUOTA] ADD [estado] [char](1) NULL;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('BVQ_BACKOFFICE.CREDITO_CARTERA_CUOTA') AND name = 'valor_pactado')
    ALTER TABLE [BVQ_BACKOFFICE].[CREDITO_CARTERA_CUOTA] ADD [valor_pactado] [money] NULL;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('BVQ_BACKOFFICE.CREDITO_CARTERA_CUOTA') AND name = 'tasa')
    ALTER TABLE [BVQ_BACKOFFICE].[CREDITO_CARTERA_CUOTA] ADD [tasa] [float] NULL;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('BVQ_BACKOFFICE.CREDITO_CARTERA_CUOTA') AND name = 'abono')
    ALTER TABLE [BVQ_BACKOFFICE].[CREDITO_CARTERA_CUOTA] ADD [abono] [money] NULL;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('BVQ_BACKOFFICE.CREDITO_CARTERA_CUOTA') AND name = 'id_credito')
    ALTER TABLE [BVQ_BACKOFFICE].[CREDITO_CARTERA_CUOTA] ADD [id_credito] [varchar](20) NULL;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('BVQ_BACKOFFICE.CREDITO_CARTERA_CUOTA') AND name = 'id_numero_cuota')
    ALTER TABLE [BVQ_BACKOFFICE].[CREDITO_CARTERA_CUOTA] ADD [id_numero_cuota] [int] NULL;
