CREATE TABLE [BVQ_BACKOFFICE].[ESTRUCTURA_ISSPOL_G04](
	[Tipo_Id_Emisor] [char](1) NULL,
	[Id_Emisor] [numeric](13, 0) NULL,
	[Codigo_Instrumento] [char](2) NULL,
	[Tipo_Instrumento] [numeric](2, 0) NULL,
	[Id_Instrumento] [char](20) NULL,
	[Numero_Liquidacion] [char](20) NULL,
	[Tipo_Transaccion] [char](1) NULL,
	[Fecha_Transaccion] [date] NULL,
	[Interes_Acumulado] [numeric](15, 2) NULL,
	[Precio_Mercado] [numeric](5, 2) NULL,
	[Valor_AccionHoy] [numeric](7, 2) NULL,
	[Valor_Mercado] [numeric](15, 2) NULL,
	[Valor_Capital] [numeric](15, 2) NULL,
	[Valor_Pago_Cupon] [numeric](15, 2) NULL,
	[Dividendo_Acciones] [numeric](10, 2) NULL,
	[Dividendo_Efectivo] [numeric](15, 2) NULL,
	[Fecha_Ultimo_Pago] [date] NULL,
	[Saldo_Valor_Nominal] [numeric](15, 2) NULL,
	[Dias_Transcurridos] [numeric](4, 0) NULL,
	[Dias_Vencer] [numeric](4, 0) NULL,
	[Valor_Efectivo_Libros] [numeric](15, 2) NULL,
	[Fuente_Cotizacion] [char](1) NULL,
	[Calificacion_Riesgo] [char](1) NULL,
	[Calificadora_Riesgo] [numeric](1, 0) NULL,
	[Fecha_Ultima_Calificacion] [date] NULL,
	[Valor_Deteriorado] [numeric](15, 2) NULL,
	[Saldo_Provision] [numeric](15, 2) NULL
) ON [PRIMARY]
