CREATE TABLE [BVQ_BACKOFFICE].[ESTRUCTURA_ISSPOL_G05](
	[Tipo_Id] [char](1) NULL,
	[Identificacion] [char](13) NULL,
	[Codigo_Instrumento] [char](2) NULL,
	[Tipo_Instrumento] [numeric](2, 0) NULL,
	[Numero_Contrato] [char](20) NULL,
	[Numero_Inversion] [numeric](3, 0) NULL,
	[Nombre_Fideicomiso] [char](70) NULL,
	[Nombre_Corto_Fideicomiso] [char](50) NULL,
	[Fecha_Constitucion] [date] NULL,
	[Fecha_Inscripcion] [date] NULL,
	[Tipo_Fideicomiso] [numeric](1, 0) NULL,
	[Duracion_Fideicomiso] [numeric](2, 0) NULL,
	[Periodicidad_Rendicion_Cuentas] [char](2) NULL,
	[Ultimo_Periodo_Rendicion] [date] NULL,
	[Periodicidad_Estados_Financieros] [char](2) NULL,
	[Ultimo_Periodo] [date] NULL,
	[Fecha_Ultima_Auditoria] [date] NULL,
	[Nombre_Fiduciaria] [char](50) NULL,
	[Activos] [numeric](15, 2) NULL,
	[Pasivos] [numeric](15, 2) NULL,
	[Patrimonio_Autonomo] [numeric](15, 2) NULL,
	[Saldo_Otros] [numeric](15, 2) NULL,
	[Saldo_Fiduciarios] [numeric](15, 2) NULL,
	[Fecha_Liquidacion] [date] NULL,
	[Valores_Restituidos_Efectivo] [numeric](15, 2) NULL,
	[Valores_Restituidos_Bienes] [numeric](15, 2) NULL
) ON [PRIMARY]

