 IF NOT EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = 'BVQ_BACKOFFICE'
      AND TABLE_NAME = 'HISTORICO_TITULOS_PORTAFOLIO'
      AND COLUMN_NAME = 'HTP_DIVIDENDO'
)
BEGIN
    ALTER TABLE [BVQ_BACKOFFICE].[HISTORICO_TITULOS_PORTAFOLIO]
    ADD HTP_DIVIDENDO BIT NOT NULL DEFAULT 0;
END
