if not exists(select * from bvq_administracion.firma)
begin
	SET IDENTITY_INSERT [BVQ_ADMINISTRACION].[FIRMA] ON 
	INSERT [BVQ_ADMINISTRACION].[FIRMA] ([FIR_ID], [FIR_NOMBRE], [FIR_CARGO], [FIR_FECHA_VINCULACION], FIR_SUBROGANTE) VALUES (1, N'Tnte. Ing. Katherine Toapanta Vilcaguano', N'DIRECTOR ECONÓMICO FINANCIERO', CAST(N'1990-01-01T00:00:00.000' AS DateTime),0)
	INSERT [BVQ_ADMINISTRACION].[FIRMA] ([FIR_ID], [FIR_NOMBRE], [FIR_CARGO], [FIR_FECHA_VINCULACION], FIR_SUBROGANTE) VALUES (2, N'Eco. Guillermo Velez Medranda', N'JEFE DE INVERSIONES', CAST(N'1990-01-01T00:00:00.000' AS DateTime),0)
	INSERT [BVQ_ADMINISTRACION].[FIRMA] ([FIR_ID], [FIR_NOMBRE], [FIR_CARGO], [FIR_FECHA_VINCULACION], FIR_SUBROGANTE) VALUES (3, N'Sgos. Ing. Elizabeth Correa Cañar', N'ANALISTA DE INVERSIONES', CAST(N'1990-01-01T00:00:00.000' AS DateTime),0)

	SET IDENTITY_INSERT [BVQ_ADMINISTRACION].[FIRMA] OFF
end

if not exists(select * from BVQ_ADMINISTRACION.firma where fir_subrogante=1)
begin
	INSERT [BVQ_ADMINISTRACION].[FIRMA] ([FIR_NOMBRE], [FIR_CARGO], [FIR_FECHA_VINCULACION], FIR_SUBROGANTE) VALUES (N'Eco. Guillermo Velez Medranda', N'DIRECTOR ECONÓMICO FINANCIERO', CAST(N'2025-06-30T00:00:00.000' AS DateTime),1)
	INSERT [BVQ_ADMINISTRACION].[FIRMA] ([FIR_NOMBRE], [FIR_CARGO], [FIR_FECHA_VINCULACION], FIR_SUBROGANTE) VALUES (N'Ing. Patricia Alcivar Cajas', N'JEFE DE INVERSIONES', CAST(N'2025-06-30T00:00:00.000' AS DateTime),1)
end