CREATE TABLE [dbo].[RETRASO]
(
	[RETR_ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [RETR_TPO_ID] INT NOT NULL, 
    [RETR_FECHA_ESPERADA] DATETIME NOT NULL, 
    [RETR_FECHA_COBRO] DATETIME NOT NULL 
)
