if object_id('bvq_administracion.sector_isspol') is null
begin
	create table BVQ_ADMINISTRACION.SECTOR_ISSPOL(
		  SCI_ID int primary key identity
		, SCI_NOMBRE varchar(100) not null
		, SCI_ORD int not null unique
	)

	insert into BVQ_ADMINISTRACION.SECTOR_ISSPOL
	(SCI_NOMBRE, SCI_ORD)
	select SCI_NOMBRE, SCI_ORD from
	(
		VALUES
		 ('ACCIONES',1)
		,('INVERSIONES DE RENTA FIJA EN EL SECTOR PRIVADO',2)
		,('INVERSIONES DE RENTA FIJA EN EL SECTOR PUBLICO',3)
		,('TÍTULOS EMITIDOS POR INSTITUCIONES FINANCIERAS',4)
		,('CERTIFICADOS DE DEPÓSITOS OBL. EMITIDAS POR ENTIDADES NO FINANCIERAS',5)
		,('OTRAS INVERSIONES DE RENTA FIJA EN EL SECTOR PRIVADO',6)
		,('INVERSIONES DE RENTA VARIABLE EN EL SECTOR PRIVADO',7)
		,('CUENTAS POR COBRAR OTROS FONDOS ISSFA',8)
		,('CUENTAS POR COBRAR OTROS',9)
		,('OTRAS',10)
	) sectoresIsspol(SCI_NOMBRE, SCI_ORD)
	where not exists(select * from bvq_administracion.sector_isspol)
end