-- Cabecera
IF OBJECT_ID('BVQ_BACKOFFICE.ISSPOL_PROYECCION_DISP_DET', 'U') IS NOT NULL
    DROP TABLE BVQ_BACKOFFICE.ISSPOL_PROYECCION_DISP_DET
IF OBJECT_ID('BVQ_BACKOFFICE.ISSPOL_PROYECCION_DISP_SAL', 'U') IS NOT NULL
    DROP TABLE BVQ_BACKOFFICE.ISSPOL_PROYECCION_DISP_SAL
IF OBJECT_ID('BVQ_BACKOFFICE.ISSPOL_PROYECCION_DISP_CAB', 'U') IS NOT NULL
    DROP TABLE BVQ_BACKOFFICE.ISSPOL_PROYECCION_DISP_CAB

-- Proyecciones manuales del Reporte de Disponibilidad ISSPOL

-- Cabecera
CREATE TABLE BVQ_BACKOFFICE.ISSPOL_PROYECCION_DISP_CAB
(
    PDC_ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ISSPOL_PROYECCION_DISP_CAB PRIMARY KEY,
    PDC_NOMBRE VARCHAR(200) NOT NULL,
    PDC_FECHA_CORTE DATE NOT NULL,
    PDC_FECHA_INICIO DATE NOT NULL,
    PDC_FECHA_FIN DATE NOT NULL,
    CONSTRAINT CK_PDC_FECHAS CHECK (PDC_FECHA_FIN >= PDC_FECHA_CORTE)
)

-- Detalle: proyecciones manuales
CREATE TABLE BVQ_BACKOFFICE.ISSPOL_PROYECCION_DISP_DET
(
    PDD_ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ISSPOL_PROYECCION_DISP_DET PRIMARY KEY,
    PDD_PDC_ID INT NOT NULL, -- FK a la cabecera
    PDD_FECHA_VENCIMIENTO DATE NOT NULL,
    PDD_PORTAFOLIO VARCHAR(200) NULL, -- fondo
    PDD_SUBTIPO VARCHAR(200) NULL, -- itc_valor
    PDD_TIPO_PAPEL VARCHAR(200) NULL,
    PDD_IE VARCHAR(20) NULL, -- '1 Ingreso' / '2 Egreso'
    PDD_MONTO MONEY NOT NULL, -- con signo (egreso negativo), igual que "cupon"
    CONSTRAINT FK_PDD_PDC FOREIGN KEY (PDD_PDC_ID)
        REFERENCES BVQ_BACKOFFICE.ISSPOL_PROYECCION_DISP_CAB (PDC_ID) ON DELETE CASCADE
)

-- Saldo final por fondo (saldo al día final del pivot), vinculado a la cabecera
CREATE TABLE BVQ_BACKOFFICE.ISSPOL_PROYECCION_DISP_SAL
(
    PDS_ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_ISSPOL_PROYECCION_DISP_SAL PRIMARY KEY,
    PDS_PDC_ID INT NOT NULL, -- FK a la cabecera
    PDS_PORTAFOLIO VARCHAR(200) NOT NULL, -- fondo
    PDS_FECHA DATE NOT NULL, -- día al que corresponde el saldo (último día del pivot para ese fondo)
    PDS_SALDO_FINAL MONEY NOT NULL, -- saldo_final_dia
    CONSTRAINT FK_PDS_PDC FOREIGN KEY (PDS_PDC_ID)
        REFERENCES BVQ_BACKOFFICE.ISSPOL_PROYECCION_DISP_CAB (PDC_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_PDS_PDC_PORTAFOLIO UNIQUE (PDS_PDC_ID, PDS_PORTAFOLIO)
)

-- Índices
CREATE INDEX IX_PDC_FECHA_CORTE
    ON BVQ_BACKOFFICE.ISSPOL_PROYECCION_DISP_CAB (PDC_FECHA_CORTE)

CREATE INDEX IX_PDC_NOMBRE
    ON BVQ_BACKOFFICE.ISSPOL_PROYECCION_DISP_CAB (PDC_NOMBRE)

CREATE INDEX IX_PDD_PDC_ID
    ON BVQ_BACKOFFICE.ISSPOL_PROYECCION_DISP_DET (PDD_PDC_ID)

CREATE INDEX IX_PDS_PDC_ID
    ON BVQ_BACKOFFICE.ISSPOL_PROYECCION_DISP_SAL (PDS_PDC_ID)
