CREATE TABLE [BVQ_BACKOFFICE].[evtTemp](
	[oper] [int] NOT NULL,
	[htp_id] [bigint] NULL,
	[es_vencimiento_interes] [int] NOT NULL,
	[fecha] [datetime] NULL,
	[montoOper] [float] NULL,
	[vep_valor_efectivo] [float] NOT NULL,
	[en_liquidez] [int] NOT NULL,
	[por_id] [int] NULL,
	[saldo_liquidez] [float] NULL,
	[saldo_liquidez2] [float] NULL,
	[voucher_exists] [int] NOT NULL,
	[lip_cliente_id] [int] NULL,
	htp_tpo_id int null,
	fecha_compra datetime null,
	liq_compra varchar(50) null
	,

	[htp_fecha_operacion] [datetime] NULL,
	[tasa_cupon] [float] NULL,
	[porv_retencion] [float] NULL,
	[iAmortizacion] [float] NULL
	,

	[nombre] [varchar](150) NULL,
	[por_codigo] [varchar](20) NULL,
	[liquidez_descripcion] [varchar](500) NULL,
	[ems_nombre] [varchar](200) NULL,
	[grc_codigo] [varchar](20) NULL,
	[tvl_codigo] [varchar](20) NULL,
	[tiv_fecha_vencimiento] [datetime] NULL,
	[tiv_tipo_valor] [int] NULL,
	[tpo_numeracion] [varchar](250) NULL,
	htp_numeracion_clean varchar(250) null,
	por_tipo int,
	tpo_categoria int
	,

	[vep_id] [int] NULL,
	vep_fecha datetime NULL,
	vep_cta_id int NULL,
	[vep_other_account] [varchar](200) NULL,
	[amount] [float] NULL,
	[account] [varchar](300) NULL,
	[vep_renovacion] [varchar](10) NULL,
	[ttl_id] [int] NULL,
	[vep_observaciones] [varchar](max) NULL,
	[ttl_nombre] [varchar](200) NULL,
	[lip_retencion] [float] NULL,
	[com_id] [int] NULL,
	[lip_documento] [varchar](50) NULL,
	[cliente_nombre] [varchar](255) NULL,
	evp_id int null,
	en_espera int null,
	liq_retencion float null,
	
	tvl_nombre varchar(100),
	liq_numero_bolsa varchar(50),
	
	liq_ret_bolsa float,
	liq_ret_casa float,
	ret_codigo varchar(100),
	valefeoper float,
	liq_total_interes float,
	liq_comision_casa float,
	liq_comision_bolsa float,
	aplica_retencion bit
) ON [PRIMARY]