CREATE TABLE [BVQ_ADMINISTRACION].[FIRMA](
	[FIR_ID] [int] IDENTITY(1,1) NOT NULL,
	[FIR_NOMBRE] [nvarchar](50) NULL,
	[FIR_CARGO] [nvarchar](50) NULL,
	[FIR_FECHA_VINCULACION] [datetime] NULL,
 CONSTRAINT [PK_FIRMA] PRIMARY KEY CLUSTERED 
(
	[FIR_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
